FROM node:20-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci --only=production

# Устанавливаем y-websocket глобально
RUN npm install -g y-websocket

EXPOSE 1234

CMD ["y-websocket"]
