apiVersion: v1
kind: Service
metadata:
  name: cocode-service
  namespace: cocode-ns
spec:
  selector:
    app: cocode-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP